name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0' 

      - name: Install dependencies
        run: |
          npm install -g firebase-tools  # Installe Firebase CLI
          npm install  # Installe les dépendances de ton projet

      - name: Authenticate to Firebase
        run: firebase login:ci --token ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Utilise ton token secret GitHub pour l'authentification Firebase

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting  # Déploie uniquement le site sur Firebase Hosting
